# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(284, 309)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        Form.setFont(font)
        self.equalButton = QtWidgets.QPushButton(Form)
        self.equalButton.setGeometry(QtCore.QRect(220, 250, 41, 41))
        self.equalButton.setObjectName("equalButton")
        self.num6 = QtWidgets.QPushButton(Form)
        self.num6.setGeometry(QtCore.QRect(120, 150, 41, 41))
        self.num6.setObjectName("num6")
        self.num3 = QtWidgets.QPushButton(Form)
        self.num3.setGeometry(QtCore.QRect(120, 200, 41, 41))
        self.num3.setObjectName("num3")
        self.subtractButton = QtWidgets.QPushButton(Form)
        self.subtractButton.setGeometry(QtCore.QRect(170, 200, 41, 41))
        self.subtractButton.setObjectName("subtractButton")
        self.num4 = QtWidgets.QPushButton(Form)
        self.num4.setGeometry(QtCore.QRect(20, 150, 41, 41))
        self.num4.setObjectName("num4")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(170, 250, 41, 41))
        self.addButton.setObjectName("addButton")
        self.num8 = QtWidgets.QPushButton(Form)
        self.num8.setGeometry(QtCore.QRect(70, 100, 41, 41))
        self.num8.setObjectName("num8")
        self.moduloButton = QtWidgets.QPushButton(Form)
        self.moduloButton.setGeometry(QtCore.QRect(220, 100, 41, 41))
        self.moduloButton.setObjectName("moduloButton")
        self.num9 = QtWidgets.QPushButton(Form)
        self.num9.setGeometry(QtCore.QRect(120, 100, 41, 41))
        self.num9.setObjectName("num9")
        self.num2 = QtWidgets.QPushButton(Form)
        self.num2.setGeometry(QtCore.QRect(70, 200, 41, 41))
        self.num2.setObjectName("num2")
        self.display = QtWidgets.QLineEdit(Form)
        self.display.setGeometry(QtCore.QRect(20, 20, 241, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.display.setFont(font)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setDragEnabled(True)
        self.display.setObjectName("display")
        self.divideButton = QtWidgets.QPushButton(Form)
        self.divideButton.setGeometry(QtCore.QRect(170, 100, 41, 41))
        self.divideButton.setObjectName("divideButton")
        self.multiplyButton = QtWidgets.QPushButton(Form)
        self.multiplyButton.setGeometry(QtCore.QRect(170, 150, 41, 41))
        self.multiplyButton.setObjectName("multiplyButton")
        self.num1 = QtWidgets.QPushButton(Form)
        self.num1.setGeometry(QtCore.QRect(20, 200, 41, 41))
        self.num1.setObjectName("num1")
        self.num5 = QtWidgets.QPushButton(Form)
        self.num5.setGeometry(QtCore.QRect(70, 150, 41, 41))
        self.num5.setObjectName("num5")
        self.num7 = QtWidgets.QPushButton(Form)
        self.num7.setGeometry(QtCore.QRect(20, 100, 41, 41))
        self.num7.setObjectName("num7")
        self.num0 = QtWidgets.QPushButton(Form)
        self.num0.setGeometry(QtCore.QRect(20, 250, 91, 41))
        self.num0.setObjectName("num0")
        self.decimalButton = QtWidgets.QPushButton(Form)
        self.decimalButton.setGeometry(QtCore.QRect(120, 250, 41, 41))
        self.decimalButton.setObjectName("decimalButton")
        self.reciprocalButton = QtWidgets.QPushButton(Form)
        self.reciprocalButton.setGeometry(QtCore.QRect(220, 150, 41, 41))
        self.reciprocalButton.setObjectName("reciprocalButton")
        self.clearButton = QtWidgets.QPushButton(Form)
        self.clearButton.setGeometry(QtCore.QRect(220, 200, 41, 41))
        self.clearButton.setObjectName("clearButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.equalButton.setText(_translate("Form", "="))
        self.num6.setText(_translate("Form", "6"))
        self.num3.setText(_translate("Form", "3"))
        self.subtractButton.setText(_translate("Form", "-"))
        self.num4.setText(_translate("Form", "4"))
        self.addButton.setText(_translate("Form", "+"))
        self.num8.setText(_translate("Form", "8"))
        self.moduloButton.setText(_translate("Form", "%"))
        self.num9.setText(_translate("Form", "9"))
        self.num2.setText(_translate("Form", "2"))
        self.divideButton.setText(_translate("Form", "/"))
        self.multiplyButton.setText(_translate("Form", "*"))
        self.num1.setText(_translate("Form", "1"))
        self.num5.setText(_translate("Form", "5"))
        self.num7.setText(_translate("Form", "7"))
        self.num0.setText(_translate("Form", "0"))
        self.decimalButton.setText(_translate("Form", "."))
        self.reciprocalButton.setText(_translate("Form", "1/x"))
        self.clearButton.setText(_translate("Form", "C"))

